config/routes.rb
Rails.application.routes.draw do
  root 'cards#index'
  resources :cards do
    get 'delete'
  end

end

app/models/card.rb
class Card < ActiveRecord::Base
  require "active_merchant/billing/rails"

  attr_accessor :add_credit, :remove_credit

  validates :cc_num, presence: true, on: :create
  validates :company, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }

  validate  :valid_card, on: :create
  validate :add_credit, on: :update
  validate  :remove_credit, on: :update

  def credit_card
  	@card = ActiveMerchant::Billing::CreditCard.new(
    		first_name: 'Tom',
    		last_name: 'Tom',
    		month: '1',
    		year: '2025',
        brand: 'visa',
        number: cc_num,
    		verification_value: '123',
    )
  end

  def last_four
    self.cc_num.gsub(/(\d+)(\d{4})/, "\\1").gsub(/\d/, "x") + self.cc_num.gsub(/\d+(\d{4})/, "\\1")
  end

  def valid_card
    unless credit_card.valid?
      errors.add(:base, "The bogus credit card you added doesn't fly.")
    end
  end
  
  def add_credit=(value)
    self.update_attribute(:amount, self.amount + value.to_i)
  end

  def remove_credit=(value)
    if  self.amount >= value.to_i
      self.update_attribute(:amount, self.amount - value.to_i)
    else
      errors.add :base, "Sorry, You only have #{self.amount} credits left. You need to add some more credits before you can do that."
    end
  end

  def can_do
    response = GATEWAY.purchase(value, @card)
  end
end

# def spend_credit
#   if valid_card && self.amount >= value.to_i
#     response = GATEWAY.purchase(value, credit_card)
#     if response.success?
#       transaction = GATEWAY.capture(value, response.authorization)
#       if !transaction.success?
#         errors.add(:base, "Sorry, You only have #{self.amount} credits left. You need to add some more credits before you can do that")
#       end
#       self.update_attribute(:amount, self.amount - value.to_i)
#     else
#       errors.add(:base, "Sorry, You only have #{self.amount} credits left. You need to add some more credits before you can do that.")
#     end
#   end
# end

# def make_credit
#   if valid_card
#     response = GATEWAY.purchase(value, credit_card)
#     if response.success?
#       transaction = GATEWAY.capture(value, response.authorization)
#       if !transaction.success?
#         errors.add(:base, "Your card was declined")
#       end
#       self.update_attribute(:amount, self.amount + value.to_i)
#     else
#       errors.add(:base, "Your card was declined")
#     end
#   end
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = Card.new
  end

  def create
    @cards = Card.all
    @card = Card.create(card_params)
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @cards = Card.all
    @card = Card.find(params[:id])
    
    @card.update_attributes(card_params)
    if @card.add_credit
      flash[:success] = "You successfully added credit to the card"
      redirect_to root_path
    end

    if @card.remove_credit
      flash[:error] = "Sorry, You do not have enough credit for that"
    end
  end

  def delete
    @card = Card.find(params[:card_id])
  end

  def destroy
    @cards = Card.all
    @card = Card.find(params[:id])
    @card.destroy
  end

private
  def card_params
    params.require(:card).permit(:company, :amount, :cc_num, :add_credit, :remove_credit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete card</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @card.company %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This card", card_path(@card), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/cards/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{@card.company}" %></h3>
</div>
<%= render "form" %>

app/views/cards/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @card, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>

        <div class="form-group">
          <%= f.label :company, class:"control-label" %>
          <%= f.text_field :company, class: "form-control" %>
        </div>
        <% if params[:action] == 'new' %>
            <div class="form-group">
              <%= f.label :cc_num, class:"control-label" %>
              <%= f.text_field :cc_num, class: "form-control" %>
            </div>
        <% elsif params[:action] == 'edit' %>
            <div class="form-group">
              <%= f.label :add_credit, class:"control-label" %>
              <%= f.text_field :add_credit, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :remove_credit, class: "control-label" %>
              <%= f.text_field :remove_credit, class: "form-control" %>
            </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/cards/_index.html.erb
<% @cards.each do |card| %>
  <tr>
    <td><%= card.company %></td>
    <td><%= card.last_four %></td>
    <td><%= number_to_currency card.amount %></td>
    <td><%= link_to "Edit", edit_card_path(card), remote: true, class: "btn btn-default" %></td>
    <td><%= link_to "Delete", card_delete_path(card), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/cards/_new.html.erb
<div class="modal-header">
<h3>New Card</h3>
</div>
<%= render "form" %>

app/views/cards/_save.js.erb
$("ul.errors").html("")
<% if @card.errors.any? %>
  <% @card.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".card-index").html("<%= escape_javascript(render 'index') %>")
  $("#card-modal").modal("hide")
<% end %>

app/views/cards/create.js.erb
<%= render "save" %>

app/views/cards/delete.js.erb
$("#card-modal").html("<%= escape_javascript(render 'delete') %>")
$("#card-modal").modal("show")

app/views/cards/destroy.js.erb
<%= render 'save' %>

app/views/cards/edit.js.erb
$("#card-modal").html("<%= escape_javascript(render 'edit') %>")
$("#card-modal").modal("show")

app/views/cards/index.html.erb
<style>
.container{
  margin-top: 20px
}
</style>
<div class="container">
  <div class="well">
    <%= link_to "New card", new_card_path, remote: true, class: "btn btn-primary" %>
  </div>
  <div class="new-card"></div>
  
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Card Number</th>
        <th>Remaining Amount</th>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </thead>
    <tbody class="card-index">
      <%= render "index" %>
    </tbody>
  </table>
</div>
<div id="card-modal" class="modal fade"></div>

app/views/cards/new.js.erb
$("#card-modal").html("<%= escape_javascript(render 'new') %>")
$("#card-modal").modal("show")

app/views/cards/update.js.erb
<%= render "save" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GiftCardTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
   <% flash.each do |key, value| %>
     <div class="alert alert-<%= key %>"><%= value %></div>
   <% end %>
 </div>

<%= yield %>

</body>
</html>